name: PKGBUILD CI

on: [push, pull_request]

jobs:
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        package: 
          [
            cadical-pic, 
            glpk-cut-log, 
            libpoly-git, 
            python-cvc5, 
            symfpu-cvc5, 
            # cvc5, 
            # cvc5-bestperformance, 
            # cvc5-bin
          ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build ${{ matrix.package }} PKGBUILD
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: ${{ matrix.package }}
        aurDeps: true
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
  aur-publish:
    needs: [build-packages]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: 
          [
            cadical-pic, 
            glpk-cut-log, 
            libpoly-git, 
            python-cvc5, 
            symfpu-cvc5, 
            # cvc5, 
            # cvc5-bestperformance, 
            # cvc5-bin
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Publish AUR package ${{ matrix.package }}
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: ${{ matrix.package }}
          pkgbuild: ./${{ matrix.package }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          allow_empty_commits: false
      